### ISSUE TITLE
Stuck at install (waiting for the service to start)

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/photoprism_ynh#35] opened 2022-12-27 17:40 UTC
The install script is stuck (on multiple instances) when starting the systemd service.

I could un-stuck the script by running:
```
echo "http: starting web server at" | sudo tee /var/log/photoprism/photoprism.log
```

**Comment by Aeris1One** [comment] 2023-10-02 11:51
can reproduce on ARM64 (Hetzner cax11)

**Comment by Thovi98** [comment] 2024-11-07 15:54
I couldn't reproduce with latest release with official builds, so I will close this. Feel free to reopen if you experience this again.

**Closed by Thovi98** 2024-11-07 15:54 UTC
