### ISSUE TITLE
Failure in: namespacing: /run/systemd/unit-root/usr/lib64: No such file or directory

### ISSUE THREAD

**Issue by brimwats** [YunoHost-Apps/photoprism_ynh#29] opened 2022-09-03 02:48 UTC
Here are my logs: https://paste.yunohost.org/exahezimic

it worked until the most recent upgrade. So then I uninstalled and reinstalled and went to look for the settings yml to make tweaks on my server but...there seems to be no settings

**Comment by brimwats** [comment] 2022-09-03 02:48
unsure if related to #22

**Comment by Limezy** [comment] 2022-09-03 09:05
Hi @brimwats !
For sure it's not related to #22 
However it's probably related to the fact that we changed from a .yml file giving the settings to an .env environnement file.
Could you please first try to upgrade to 2022.09.01 just released ?
Then tell me if it's still broken.

**Comment by brimwats** [comment] 2022-09-03 15:59
> Could you please first try to upgrade to 2022.09.01 just released ?


no luck! new logs: https://paste.yunohost.org/nuqaxigami

**Comment by brimwats** [comment] 2022-09-03 16:00
I have this installed on a / domain (i.e. as main thing on the URI)

**Comment by brimwats** [comment] 2022-09-03 16:14
Here are the install logs: https://paste.yunohost.org/raw/omajofapiy

And the uninstall logs https://paste.yunohost.org/raw/igojamecec

**Comment by Limezy** [comment] 2022-09-04 07:40
https://forum.proxmox.com/threads/apache2-service-failed-to-set-up-mount-namespacing-permission-denied.56871/post-480100
Are you inside a Proxmox container ?

**Comment by brimwats** [comment] 2022-09-04 13:41
No. I have a dell poweredge server, only has yunohost

Hardware: Dell R720
I have access to my server : SSH, direct access
Are you in a special context or did you perform some particular tweaking on your YunoHost instance ? : not really. I have a RAID server, where /home = ~2TB and /var = 20TB so most of my storage needs to be on /var

**Comment by brimwats** [comment] 2022-09-04 13:43
bc most of the photos are on /var/Multimedia I usually have to edit a config file to point programs at them. 

Once Photpoprisim is up and running (haven't gotten to this part). Here's what I do:


```
sudo su

# Let's create the group and add its users

# groupadd multimedia, not necessary because it exists
usermod photoprism -a -G multimedia


# Set permissions

chown photoprism:multimedia -R /var/Multimedia
find /var/Multimedia -type d -exec chmod 0775 {} \;
find /var/Multimedia -type f -exec chmod 0664 {} \;

# Set ACLs (I did some research :p)
# Users will get ownership of their own files,
# but the group will always be multimedia
# I left the r permission to other, but you can replace it with 0
# if you only want the apps listed above to access the files

setfacl -d -m u::rwX,g::rwX,o::r /var/Multimedia

# Restart services

systemctl restart photoprism
systemctl restart php7.4-fpm
systemctl restart php8.0-fpm
systemctl restart nginx

```

**Comment by Thovi98** [comment] 2022-09-16 21:23
I’ve the exact same issue since the exact same upgrade (sorry for the delay). I didn’t touch at any configuration, and I remove/reinstall, but same error.
I don’t know how to solve this.

**Comment by Limezy** [comment] 2022-09-17 02:40
Ok I will try to reproduce and then have a look at the bug. Meanwhile you can force upgrade to an earlier release of the package

**Comment by centralscrutinizer21** [comment] 2022-09-17 07:50
same here. how to force uograde to an earlier version?

**Comment by Limezy** [comment] 2022-09-17 08:40
OK. Just tried again to install from scratch, everything is perfect.
So I'll try to install an old version then upgrade to reproduce the bug.

**Comment by Limezy** [comment] 2022-09-17 10:06
> same here. how to force upgrade to an earlier version?

It would be something like `sudo yunohost app upgrade photoprism -u https://github.com/YunoHost-Apps/photoprism_ynh/tree/261e9e2c2ec606e2d6bf724127467da09ad3d0d7 --force --debug`, to come back to version `2022.07.30~ynh3`

I'm trying to install that version `2022.07.30~ynh3` and then upgrade, hopefully I'll be able to reproduce the bug

**Comment by Limezy** [comment] 2022-09-17 12:08
Well, the bad news is that my update worked perfectly... Couldn't reproduce any bug !

**Comment by centralscrutinizer21** [comment] 2022-09-17 12:58
Yeah, and in my case downgrading to 2022.07.30~ynh3 didn't solved the issue neither

**Comment by Limezy** [comment] 2022-09-17 13:56
Which architecture are you using ? Amd64 I guess ?

**Comment by Limezy** [comment] 2022-09-17 13:57
Could you try restore from your pre upgrade backup, if you still have it ?

**Comment by brimwats** [comment] 2022-09-17 16:02
my backup no longer exists

**Comment by Limezy** [comment] 2022-09-17 16:18
It could be linked to the way I've solved #22.
Could you please share here the result of the command `sudo ls -lla /` ?

**Comment by centralscrutinizer21** [comment] 2022-09-17 16:59
> Which architecture are you using ? Amd64 I guess ?

Arm64

> Could you try restore from your pre upgrade backup, if you still have it ?

Restored the app from backup version 2022.07.30~ynh1 now is working again



> It could be linked to the way I've solved #22. Could you please share here the result of the command `sudo ls -lla /` ?

```
total 75
drwxr-xr-x  18 root root  4096 Aug  8 11:55 .           drwxr-xr-x  18 root root  4096 Aug  8 11:55 ..
lrwxrwxrwx   1 root root     7 Aug  8 11:11 bin -> usr/bin
drwxr-xr-x   3 root root  3072 Jan  1  1970 boot
drwxr-xr-x  17 root root  4080 Sep 17 13:05 dev
drwxr-xr-x 115 root root 12288 Sep 17 07:38 etc         drwxr-xr-x  23 root root  4096 Sep 15 14:44 home
lrwxrwxrwx   1 root root     7 Aug  8 11:11 lib -> usr/lib
drwx------   2 root root 16384 Aug  8 11:54 lost+found
drwxr-xr-x   2 root root  4096 Aug  8 11:11 media
drwxr-xr-x   3 root root  4096 Aug 25 20:02 mnt
drwxr-xr-x   3 root root  4096 Sep 16 17:59 opt
dr-xr-xr-x 289 root root     0 Jan  1  1970 proc
drwx------   4 root root  4096 Sep 16 17:59 root        drwxr-xr-x  37 root root  1100 Sep 17 17:31 run
lrwxrwxrwx   1 root root     8 Aug  8 11:11 sbin -> usr/sbin
drwxr-xr-x   2 root root  4096 Aug  8 11:11 srv
dr-xr-xr-x  12 root root     0 Jan  1  1970 sys
drwxrwxrwt  19 root root  4096 Sep 17 17:30 tmp
drwxr-xr-x  11 root root  4096 Aug  8 11:11 usr
drwxr-xr-x  13 root root  4096 Aug 25 23:01 var
```

**Comment by Limezy** [comment] 2022-09-18 07:51
OK, I think I understood the problem. For some reasons you don't have a `lib64 -> /usr/lib64` symlink at the root, which I have. The sandboxing function I've used in Systemd is crashing since I ask it to mount /lib64, which you don't have.
I'm trying to see if there is a way to remove this or to put that bind as optional instead

**Comment by Limezy** [comment] 2022-09-18 08:36
Could you please try to update to `2022.09.01~ynh2` ?

**Comment by brimwats** [comment] 2022-09-19 14:22
I upgraded but am still getting a 502 error. Should I try reinstalling from scratch?

**Comment by brimwats** [comment] 2022-09-19 16:52
There are no logs of the failure right now, the update happened successfully, but it's when I access the url it 502's

**Comment by brimwats** [comment] 2022-09-19 16:53
I'm happy to try a reinstall to see if I can get logs though!

**Comment by Limezy** [comment] 2022-09-19 18:24
If it's 502 it means the service is not starting well.
Normally, it will throw an error.
So you can go to Yunohost webadmin -> Services -> Photoprism
Photoprism will likely tell you that it's not running, but there the webadmin should report the last lines of the service log, which are the ones I would like to have a look into !
Thanks

**Comment by brimwats** [comment] 2022-09-19 18:43
oh duh! here it is

https://paste.yunohost.org/sonesubiqi

**Comment by brimwats** [comment] 2022-09-19 18:44
and /var/log/photoprism/photoprism.log is empty

**Comment by Limezy** [comment] 2022-09-20 11:27
Could you please try `sudo yunohost app upgrade photoprism -u https://github.com/YunoHost-Apps/photoprism_ynh/tree/fix-issue-29 --force` ?
I've put all bindings as optional...

**Comment by Thovi98** [comment] 2022-09-20 12:21
I can confirm it works for me :D

**Comment by Limezy** [comment] 2022-09-20 12:30
> I can confirm it works for me :D

Wow great !
I'm creating a PR and will merge once confirmed working by @brimwats and @centralscrutinizer21

**Comment by brimwats** [comment] 2022-09-20 17:20
it works for me!

**Comment by Limezy** [comment] 2022-09-21 08:07
@centralscrutinizer21 I have merged and will close that issue.
Please reopen it in case the fix didn't work for you.

**Closed by Limezy** 2022-09-21 08:07 UTC

**Comment by centralscrutinizer21** [comment] 2022-09-22 10:05
> @centralscrutinizer21 I have merged and will close that issue. Please reopen it in case the fix didn't work for you.

I can confirm it works for me. Great Job
